CREATE USER gl IDENTIFIED BY glpwd DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;
GRANT CREATE SESSION TO gl;
GRANT CREATE TABLE TO gl;
GRANT CREATE VIEW TO gl;
GRANT CREATE ANY TRIGGER TO gl;
GRANT CREATE ANY PROCEDURE TO gl;
GRANT CREATE SEQUENCE TO gl;
GRANT CREATE SYNONYM TO gl;
