USE [WideWorldImporters]
GO
DROP EXTERNAL TABLE cosmosdb.Orders
GO
DROP SCHEMA cosmosdb
GO
DROP EXTERNAL DATA SOURCE CosmosDB
GO
DROP DATABASE SCOPED CREDENTIAL CosmosDBCredentials
GO
DROP MASTER KEY
GO