USE [WideWorldImporters]
GO
DROP EXTERNAL TABLE azuresqldb.ModernStockItems
GO
DROP SCHEMA azuresqldb
GO
DROP EXTERNAL DATA SOURCE AzureSQLDatabase
GO
DROP DATABASE SCOPED CREDENTIAL AzureSQLDatabaseCredentials
GO
DROP MASTER KEY
GO